import sqlmodel
"""ajout de TP update
Revision ID: 00c4ccbb7714
Revises: 5e6a1e50de5a
Create Date: 2025-09-22 21:02:07.380633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c4ccbb7714'
down_revision: Union[str, None] = '5e6a1e50de5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
