import sqlmodel
"""fix: delete index de tpWrite
Revision ID: 21a20664f0de
Revises: cf7ac1ec5b7d
Create Date: 2025-09-27 09:41:52.766276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a20664f0de'
down_revision: Union[str, None] = 'cf7ac1ec5b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
