import sqlmodel
"""creation automatique des couleurs fix1
Revision ID: 590ead8374ab
Revises: bdb94cd08fd2
Create Date: 2025-09-10 20:47:07.191053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590ead8374ab'
down_revision: Union[str, None] = 'bdb94cd08fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
