import sqlmodel
"""fix CoursRead
Revision ID: 5e6a1e50de5a
Revises: d6aa7f60d996
Create Date: 2025-09-12 17:08:06.465330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6a1e50de5a'
down_revision: Union[str, None] = 'd6aa7f60d996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
