import sqlmodel
"""create TP fix3
Revision ID: 77373c4fb958
Revises: 89ac0d11ab5a
Create Date: 2025-05-12 08:11:55.162564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77373c4fb958'
down_revision: Union[str, None] = '89ac0d11ab5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tp', sa.Column('titre', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('tp', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('tp', 'nom')
    op.drop_column('tp', 'couleur')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tp', sa.Column('couleur', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tp', sa.Column('nom', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tp', 'description')
    op.drop_column('tp', 'titre')
    # ### end Alembic commands ###
