import sqlmodel
"""create TP fix2
Revision ID: 89ac0d11ab5a
Revises: 0d3ab66d9262
Create Date: 2025-05-12 07:51:05.822172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ac0d11ab5a'
down_revision: Union[str, None] = '0d3ab66d9262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tp', sa.Column('cours_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tp', 'cours', ['cours_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tp', type_='foreignkey')
    op.drop_column('tp', 'cours_id')
    # ### end Alembic commands ###
