import sqlmodel
"""creation automatique des couleurs
Revision ID: bdb94cd08fd2
Revises: 655935e04a7d
Create Date: 2025-09-10 20:44:39.129804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb94cd08fd2'
down_revision: Union[str, None] = '655935e04a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cours', 'couleur_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cours', 'couleur_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
