import sqlmodel
"""ajout de couleur id a coursReadWithTp
Revision ID: cf7ac1ec5b7d
Revises: 59f550e14664
Create Date: 2025-09-23 22:34:53.971986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7ac1ec5b7d'
down_revision: Union[str, None] = '59f550e14664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
