import sqlmodel
"""ajout couleur
Revision ID: e3543969c851
Revises: 5e4ec5963535
Create Date: 2025-09-03 07:20:44.022502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3543969c851'
down_revision: Union[str, None] = '5e4ec5963535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couleur',
    sa.Column('background_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cours', sa.Column('couleur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cours', 'couleur', ['couleur_id'], ['id'])
    op.drop_column('cours', 'couleur')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cours', sa.Column('couleur', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cours', type_='foreignkey')
    op.drop_column('cours', 'couleur_id')
    op.drop_table('couleur')
    # ### end Alembic commands ###
