services:
  backend:
    build:
      context: .
      dockerfile: ./build-prod/api/Dockerfile
    environment:
      - ENV=dev
      - DATABASE_URL=postgresql://api:lycee@database:5432/lycee
      - DATABASE_URL_ASYNC=postgresql+asyncpg://api:lycee@database:5432/lycee
      #    environment:#    environment:
#      - ENV=production
#      - DATABASE_URL=postgresql://api:lycee@database:5432/lycee
#      - CORS_ORIGINS=${CORS_ORIGINS:-https://yourdomain.com}
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: unless-stopped


  frontend:
    build:
      context: .
      dockerfile: ./build-prod/app/Dockerfile
    environment:
      - API_BASE_URL=http://127.0.0.1:8000
    ports:
      - "3000:3000"
    restart: unless-stopped

  database:
    image: postgres:latest
    command: ["postgres"]
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: lycee
      POSTGRES_DB: lycee
    volumes:
      - database-volume:/var/lib/postgresql/data



volumes:
  database-volume:
    driver: local