services:
  backend:
    build:
      context: .
      dockerfile: ./build-prod/api/Dockerfile
    environment:
      - ENV=dev
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_URL_ASYNC=${DATABASE_URL_ASYNC}
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - app-network


  frontend:
    build:
      context: .
      dockerfile: ./build-prod/app/Dockerfile
    ports:
      - 5173:5173
    restart: unless-stopped
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  database-volume:
    driver: local